wip
aptly-dev/aptly pull request #1392
Opened 2024-11-11 14:04 UTC by neolynx

Fixes https://github.com/aptly-dev/aptly/issues/1290

## Description of the Change

## Checklist

- [ ] unit-test added (if change is algorithm)
- [ ] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [ ] documentation updated
- [ ] author name in `AUTHORS`

2024-11-13 20:54 UTC, neolynx commented on azure/public.go
> +	// FIXME: check how to integrate publishedPrefix: done?
use storage.az.blobPath

2024-11-13 20:55 UTC, neolynx commented on azure/public.go
> +	return storage.internalCopyOrMoveBlob(src, dst, "SymLink", false /* do not remove src */)
fixme

2024-11-16 20:56 UTC, iofq requested changes
Need to update `debian/control` with the new azure go package

2024-11-17 13:06 UTC, neolynx commented
> Need to update `debian/control` with the new azure go package

I tried that, unfortunately the azure sdk package is lacking some modules in the latest version on debian, so this has to wait.
I am also synchronizing with the official debian packaging, and will ask if the missing go modules (mainly azure, swaggo, ..) could be provided for trixie.
The github pipeline is not building with debian dependencies, so the debian/control does not matter there...

2024-11-17 16:19 UTC, iofq commented
> > Need to update `debian/control` with the new azure go package
> 
> I tried that, unfortunately the azure sdk package is lacking some modules in the latest version on debian, so this has to wait. I am also synchronizing with the official debian packaging, and will ask if the missing go modules (mainly azure, swaggo, ..) could be provided for trixie. The github pipeline is not building with debian dependencies, so the debian/control does not matter there...

gotcha so this must just be for building from source (deb-src)?

2024-11-17 16:20 UTC, iofq approved these changes

2024-11-17 16:42 UTC, neolynx commented
> > > Need to update `debian/control` with the new azure go package
> > 
> > 
> > I tried that, unfortunately the azure sdk package is lacking some modules in the latest version on debian, so this has to wait. I am also synchronizing with the official debian packaging, and will ask if the missing go modules (mainly azure, swaggo, ..) could be provided for trixie. The github pipeline is not building with debian dependencies, so the debian/control does not matter there...
> 
> gotcha so this must just be for building from source (deb-src)?

yes, this is just for debian native build, with debian only dependencies, like molior aptly and debian official builds...

2024-11-17 17:13 UTC, merged